
version: "2"
services:

  instance1:
    image: plone
    ports:
    - 8081:8080
    depends_on:
    - zeo
    environment:
    - ZEO_ADDRESS=zeo:8080

  instance2:
    image: plone
    ports:
    - 8082:8080
    depends_on:
    - zeo
    environment:
    - ZEO_ADDRESS=zeo:8080

  zeo:
    image: plone
    command: zeo
    volumes:
    - data:/data

volumes:
  data: